### ISSUE TITLE
Wishlist: Add the ability to tell if something needed to be "cleaned" or not.

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#109]
It doesn't seem possible to test whether or not text needed to be "cleaned"

As part of the tokenization process, `bleach` returns text with the attributes alphabetized, so a string comparison is not possible.

For example:

```
>>> input = """<a href="http://example.com" title="Example Link" class="foo">Example</a>"""
>>> output = bleach.clean(input)
>>> print output
u"""<a class="foo" href="http://example.com" title="Example Link">Example</a>"""
```

so , obviously...

```
>>> input == output
False
```

This makes it impossible to track metrics regarding unsafe content submission -- or alert users if their content is unsafe.

**Comment by willkg** [comment]
If someone wants to tackle this, I suggest doing it in another library and using bleach if that helps and depending on how that effort turns out, maybe we can merge the two at some future date.

Given the above comments, I think we're at a point where it's clear this is impossible to do effectively and thus it's not something I want to add to this library.
