### ISSUE TITLE
improved callable filter support

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#126]
this is perhaps a bad title.  i'll explain the problem:

as mentioned in an earlier ticket, i needed to support the  "data-*" namespace on attributes.  the suggested route is callable filters.

the two main problems are as follows
- `*` doesn't accept callable filters.  based on the current setup, it requires an iterable.
- specific tags can have a callable filter OR a list of attributes.  not both.

both of these are invalid:

```
macro_attributes_ok = {
    '*': allowable_macro_attributes,
    'a' : ['href', 'title', 'target', 'rel', allowable_macro_attributes],
}
```

the callable_filters, as-is, must be implemented with a dedicated function per TAG.  This gets messy as a lot of code must be written.

```
macro_attributes_ok = {
    'a' : allowable_attributes_a,
    'div' : allowable_attributes_div,
    'span' : allowable_attributes_span,
}
```

approaches that could be nicer / easier to deal with:

• allow for callables to be within a list of text attributes

```
macro_attributes_ok = {
    'a' : [ 'href', 'link', allowable_attributes_setA ],
    'div' : [ 'class', 'style', allowable_attributes_setA ],
}
```

• pass the tag's name in as a kwarg to the callable.  this would allow callables to reflect the current tag -- and be backwards compatible.  

```
def filter_src(name, value, tag=None):
    if tag != 'img':
         return False
    if name in ('alt', 'height', 'width'):
        return True
```
-  the `attributes` kwarg to clean could be a callable itself; one that expects a triplet of data
  
     def validate_attribute( tag, attribute, value ):
           return True
  
    clean( text, attributes=validate_attribute)

**Comment by willkg** [comment]
I'm breaking things in Bleach 2.0 API-wise, so it's a good time to look into this.

**Comment by willkg** [comment]
Ok. I have the following thoughts:

1. It makes sense to pass in tag, attribute and value to all callables. It'll make a bunch of re-use type use cases easier.
2. I like being able to pass in a single callable, too. That's interesting.
3. I don't want to mix values and callables. It's easier implementation-wise and explanation-wise to do a list of values OR a callable. I think simpler here is good since fewer moving pieces usually means it's easier to understand the security consequences.

So given that, I'm going to implement item 1 and 2. Item 1 is backwards-incompatible--I'll make sure to note that in the `CHANGES` (2.0 is a good time to do backwards-incompatible things). Item 2

**Comment by jvanasco** [comment]
sounds good.   (1) will solve most issues.  (2) is icing on the cake.  (3) is largely irrelevant by (1), as it can be handled by user code at that point.

**Comment by DylanYoung** [comment]
Note that 3 can be implemented quite easily in user code:

```
def allowed_list_callable(allowed_list=(), subcallable=lambda *args: False):
    def combined_callable(tag, *args):
        if tag in combined_list:
            return True
        return subcallable(tag, *args)
```

As jvanasco rightly notes though, the security implications are hard to reason about.
