### ISSUE TITLE
HTML entities being unescaped

### ISSUE THREAD

**Issue by brandonrobertz** [mozilla/bleach#143]
I don't know if this is related to #130 , but I have an issue with this with non-breaking space being unescaped:

```
import bleach
bleach.clean('&nbsp;')
# results in -> u'\xa0'
```

Bleach version 1.4.1
HTML5lib version 0.999

**Comment by brandonrobertz** [comment]
I've investigated this further. It appears a transform is being done inside the html5lib tokenizer.  There's a `constants.py` file with entities that has the nbsp replacement:

    entities = {
        ...
        "nbsp": "\xa0",
        "nbsp;": "\xa0",

Then, in the tokenizer, there's a consume entity that does the dirty work:

    def consumeEntity(self, allowedChar=None, fromAttribute=False):
        # Initialise to the default output for when no entity is matched
        charStack = [self.stream.char()]

Unfortunately, bleach doesn't provide a way to override this functionality and it looks like it's difficult in the HTML5lib. As a quick band-aid, I had to do a regex replacement on `\xA0` back to `&nbsp;`.

    entity_replacements = {
        '\xa0': '&nbsp'
    }

    def swap_entities( text):
        for k, v in entity_replacements.items():
            print k, v
            text = re.sub( k, v, text)
        return text

It's not pretty, but at least I'm getting the result I need.

Also, this is the same thing causing #130, I've confirmed that the same `consumeEntity` code runs when you do (code from #130):

    bleach.linkify('&lt;br&gt; http://example.com')
    # dbg:charStack [u'l', u't', u';', u'b']
    # dbg:entityName lt;
    # dbg:replacing &lt; with entities[entityName] <
    # -> <br> <a href="http://example.com" rel="nofollow">http://example.com</a>

**Comment by jsocol** [comment]
No this is definitely not desired behavior for this use case. I'm digging into it now, thanks for doing this research!

**Comment by jsocol** [comment]
I think this is another thing where we have to copy and change the implementation of a core method. Subclassing sucks sometimes.

**Comment by jsocol** [comment]
I no longer think this is connected to #130. That has a root cause specific to how `linkify` constructs new nodes. (Well, they're "connected" in that both are dealing with a parsed text representation of PCDATA.)

In #130, what happens is a text node gets mangled, then parsed, instead of being treated as a text node. This only happens in linkify.

Here, I think we're dealing with a problem on the serialization end, where entities are coming back as the character they represent (in this case `\xa0`) instead of as the original entity. `resolve_entities=False` on the serializer doesn't seem to fix it, though. Somehow, it looks like we're losing the distinct node type of `Entity`.

**Comment by willkg** [comment]
I don't understand the problem here. Even so, I'm not sure there's much we could do about it and I'm not sure what we would do about it would involve API-breaking things which I'm trying to pile up into the 2.0 release.

Given that, I'm going to bump this out of the 2.0 milestone so that we can get that out.

**Comment by brandonrobertz** [comment]
I no longer rely on this issue getting resolved, but it's a problem because there's no good reason (perhaps I'm wrong?) why `bleach.clean` should take valid, allowed markup and turn it into raw binary characters. `&nbsp;` shouldn't be cleaned. That said, the issue does appear to be further up in the chain, so there's not much that can be done about that. The proposed mitigation for users who don't want this specific functionality was to allow users to override the consumed entities, per "band-aid" above.

**Comment by brandonrobertz** [comment]
I no longer rely on this issue, but the issue here is why is `bleach.clean`, which normally turns representations like this `'an <script>evil()</script> example'` into this `'an &lt;script&gt;evil()&lt;/script&gt; example'` doing the opposite in this case? Normally when we encounter valid markup, we ignore it, not convert it to it's character representation.

**Comment by brandonrobertz** [comment]
Also, proposed "band-aid" above simply allowed users to override this behavior *after* it's been performed upstream.

**Comment by jvanasco** [comment]
Here's a variant... with a simplified example:

    >>> payload = '&#39;&#34;'
    >>> bleached = bleach.clean(payload)
    >>> print bleached
    '"

If the output is destined for HTML tag attributes, this could allow for a mischief maker to carefully craft an evil payload.

We broke some html pages with our admin console, because a "sanitize_input" function from the user side was recycled into the admin side, with the entities converted before bleach and data cached (to avoid escaping on every usage).   The fix was a simple 2 line swap.  We had unit tests that passed on A and B, but nothing covered A+B (now we obviously do).

IMHO, there should be a warning note that html entities may be converted.  

In the future, a kwarg to escape/unescape all entities (or provide a mapping) would be nice.

**Comment by willkg** [comment]
As a reminder, we have a process for reporting security issues detailed here:

* https://github.com/mozilla/bleach#reporting-bugs
* https://bleach.readthedocs.io/en/latest/#reporting-bugs

Please don't report possible security vulnerabilities in public places.

**Comment by willkg** [comment]
Relatedly, https://github.com/mozilla/bleach/issues/291#issue-240999476 is the same issue.

```
import bleach
bleach.clean('http://example.com?active=true&current=true')
# Out: u'http://example.com?active=true\xa4t=true'
```

The reporter is using bleach 1.4.3, html5lib 0.99 and python 2.7.6. We don't support that version of Bleach and html5lib anymore, but this is still a problem with bleach 2.0 and html5lib 0.99999999 (8 9s).

**Comment by brandonrobertz** [comment]
Are all related issues getting closed? Is this ever getting fixed? Or is there a parent issue (non-linked) and I'm unaware of that fixes this?

**Comment by jvanasco** [comment]
> Please don't report possible security vulnerabilities in public places

I considered that and did a few proof of concepts before deciding where to post.  I couldn't find any potential for a security issue in whole or part, just "mischief" from breaking tags in a specific way under very small usage conditions which include "improper use of the library".

**Comment by jvanasco** [comment]
I tossed together a quick script to run all the 'text' html entities and the standard numeric range through `bleach.clean()`

the only entities that are remain unconverted:

	&amp;
	&gt;
	&lt;

additionally, these numeric encodings are transcoded to entities:

	&#38; -> &amp;
	&#60; -> &lt;
	&#62; -> &gt;

If I can find some time I'll dig into the source for a PR and/or some new unit tests.  While I'm very familiar with the 1.x branch, I haven't looked at the 2.x rewrite yet, so I'll need to block out a chunk of time.

If anyone else beats me to it, hopefully this helps in pinpointing which section/library is handling it.

**Comment by willkg** [comment]
@jvanasco, @brandonrobertz: Can you look at PR #293? Does that work for you?

**Comment by jvanasco** [comment]
actively going through this...  I'll have input in a few hours.

**Comment by brandonrobertz** [comment]
Went through the PR and it looks good to me @willkg thanks for the effort.
