### ISSUE TITLE
Disabled test

### ISSUE THREAD

**Issue by ShriramK** [mozilla/bleach#191]
mentioned  at https://coffeeonthekeyboard.com/bleach-html-sanitizer-and-auto-linker-for-django-344/
is that already fixed ?

**Comment by willkg** [comment]
I didn't write that blog post and I'm not sure what disabled test he's talking about specifically. I skimmed the tests and don't see any that are disabled. Given that, I'm going to close this out.

If you want, you can pull down the git repo, wind it back to a commit around the time of that blog post and then look at the tests to see which are disabled and then see if it was fixed or removed since then.
