### ISSUE TITLE
linkify hanging for this string:

### ISSUE THREAD

**Issue by guybowden** [mozilla/bleach#200]
With fresh install of bleach (1.4.3) in a new virtualenv:

```
>>> import bleach
>>> bleach.linkify("an@email.com<mailto:an@email.com>", parse_email=True)
... hangs ...
```

(found because I have it linkifying emails - and this came through in someone's sig)

**Comment by blag** [comment]
@guybowen Just FYI: flipping `parse_email` to `False` doesn't hang and seems to return more sensible results than the fixed (non-hanging) result in PR #221 with `parse_email=True`.

Are you reporting *just* the hang behavior, or the hang behavior *and* the non-sensible result? I'm just trying to figure out if I fixed it properly or not. Thanks!

**Comment by willkg** [comment]
I spent some time looking into this. The test case I'm using looks like this:

```
def test_hang():
    assert (
        linkify("an@email.com<mailto:an@email.com>", parse_email=True) ==
        ''
    )
```

I think there are a few things about this string that are causing problems. First is that there is an email address in the `.text` of the first node. Second is that the email address happens twice, so when `.linkify()` does `re.sub()`, that replaces all the instances of the email address which causes the loops to just keep growing.

We should probably look at passing in `count=` as an argument to `re.sub()`. I don't think that'll fix this, but it seems like it should be just replacing the first one anyhow.

There's a recursion on `.linkify_nodes()` that surprises me since it doesn't reduce the tree at all in the recursion step. That's fishy, too.

Anyhow, I don't want to spend more time on this for 1.5, so I'm going to bump it.

**Comment by guybowden** [comment]
@blag I will take a look - I guess the expected output should be two email addresses linked up with &gt; and &lt; around them? For my usage I need to have `parse_email=True` in order that a regular email address in the text will be linked up.

**Comment by willkg** [comment]
Tossing this in the v2.0 milestone to look into whether the rewrite affects the hang.
