### ISSUE TITLE
Bleach.clean removes img src with html5lib==0.999

### ISSUE THREAD

**Issue by kvdveer** [mozilla/bleach#211]
With `html5lib==0.999`

```
>>> import bleach
>>> bleach.clean("<img src=\"data:123\">", attributes={'img':['src']}, tags=['img'])
'<img>'
```

With `html5lib==0.9999`

```
>>> import bleach
>>> bleach.clean("<img src=\"data:123\">", attributes={'img':['src']}, tags=['img'])
'<img src="data:123">'
```

I'd suggest updating the minimum requirement.

**Comment by willkg** [comment]
I haven't looked at this at all. Is this a problem with just `data:` urls or does it affect `http:` urls, too?

**Comment by willkg** [comment]
@kvdveer ^^^ Can you or someone else answer that?

**Comment by willkg** [comment]
I looked into it. It is the `data:` protocol use. If you allow that, then it works as I would expect it to:

```
>>> bleach.clean("<img src=\"data:123\">", attributes={'img':['src']}, tags=['img'], protocols=['data'])
u'<img src="data:123">'
>>>
```

The `protocols` argument will be in bleach 1.5. It hasn't been released, yet.

https://bleach.readthedocs.io/en/latest/changes.html

Given that this is fixed in master, I'm going to close it out. Thank you!
