### ISSUE TITLE
plan for bleach support for latest html5lib

### ISSUE THREAD

**Issue by jonathanmorgan** [mozilla/bleach#217]
Hello,

I don't know the right way to broach this topic, so I apologize if this should be posted elsewhere first, but I'm trying to figure out what the plan is for bleach to support the latest html5lib (not sure if we'd call that the "upcoming 1.0", or if that is sort of a misnomer since it has been in beta for over a year), and if there is anything I can do to help.  So, is there a plan, and if so, can I help?

I think, in issue https://github.com/mozilla/bleach/pull/195, the html5lib developer implies that the change captured in pull request https://github.com/html5lib/html5lib-python/pull/110 is the last one that will impact bleach for a while.  Does that mean it could be time to try to get bleach to work with the latest html5lib, or are you still waiting to see if there are more changes needed?

Sorry if this has already been discussed elsewhere, but I wasn't sure of the resolution for this based on issue https://github.com/mozilla/bleach/issues/212.

Thanks,

Jon

**Comment by willkg** [comment]
Bleach has a pretty small set of issues in the tracker. In  this comment:

https://github.com/mozilla/bleach/issues/212#issuecomment-233992684

you asked if there was an issue for updating bleach to work with the future plans of html5lib. I figured you'd checked the issue tracker and answered your own question. My apologies if that wasn't the case.

I was figuring that the html5lib 1.0 milestone was the thing we should be targeting because i didn't really want to deal with supporting a bunch of different versions of html5lib with varying numbers of 9s. The status of that milestone is here:

https://github.com/html5lib/html5lib-python/milestone/1

I don't know if that's a firm promise or whether that milestone is a moving target, but I figure that since it's set for the beginning of September, the best thing to do is just wait until we make any plans for bleach.

In the meantime, you can see we have a 1.5 milestone:

https://github.com/mozilla/bleach/milestone/5

Work on that has stalled as I've been busy with other things and no one else is currently active on bleach as far as I can tell.

I think that covers everything! Hope that helps!

**Comment by jonathanmorgan** [comment]
OK.  Thanks for the information.  Sorry to make you spell it out.  I use github, but I'm not well-versed in all the infrastructure it brings on top of git.

I am using bleach to strip HTML but leave some tags and attributes in, and I've not found a good replacement, so I'd be willing to help if it helps to keep things moving.  I'm in the midst of a busy couple of weeks moving and switching jobs, though, so I probably won't have much bandwidth until middle of September.

I guess first question is, would you be open to me trying to help?  If so, would a good start be to look over the issues in the 1.5 milestone?  A cursory glance suggests 200 and 161 might be of modest enough scope that I could look into them to get an introduction.

**Comment by willkg** [comment]
No worries! I didn't mean to imply you did anything wrong. Getting the hang of these tools takes a while--there's nothing wrong with that. Plus GitHub keeps changing, so we're all in a perpetual state of getting the hang of it.

I really could use some help on bleach. I want to get v1.5 out, but haven't had time to spend on finishing it up. Any help with any of the 1.5 milestone issues would be super. Even just poking around and then adding a comment with what you've observed or adding a test case or anything that moves the issue forward or clarifies it in some way is helpful. I'll try to be prompt with replies to any questions you have or comments, but my availability for the next few weeks is spotty.

I've got a ton of stuff to do in the next two days, then I'm on PTO for a week. After that I'm traveling for work. After that, we're in mid-September and I can spend some quality time on bleach, get 1.5 out and work with you to figure out what we need to do to support html5lib 1.0.

**Comment by jonathanmorgan** [comment]
OK.  My next couple of weeks are really busy, as well (moving to NYC from Detroit area with newborn, new job, and trying to finish off PhD that just won't die).  I should have time to start looking at the milestone issues later within the next couple of weeks, though.

**Comment by jonathanmorgan** [comment]
OK.  Finally getting settled in here in the city.  So, I'll try to go over the issues in the next few days and see if I can add anything to what is there now.

Looks like there hasn't been much progress on html5lib in terms of commits since we last commented.  Think we should still wait on 1.0?

**Comment by willkg** [comment]
OMG. My September was crazy. This is the last week of the quarter and I'm scrambling to finish a big project. October should be saner.

I think it behooves us to wait until html5lib 1.0 is out before we go do things, but I don't know what the current state is, either.

If no one chimes in more definitively here, I'll look into it next week and offer more thoughts then.

**Comment by blag** [comment]
I just created a PR that finishes up the last requirement for html5lib's milestone 1, so hopefully their version 1.0 will be out soon.

**Comment by blag** [comment]
Okay, so my PR for html5lib might not make it in, but it's purely adding a license to every file and a license check to the travis configuration. Nothing that would impact bleach behavior-wise.

html5lib hasn't seen a non-negligible commit since July, so I don't think it's going to be changing all that much more anytime soon.

Could we remove the `html5lib...<0.99999999` constraint from [this line](https://github.com/mozilla/bleach/blob/master/setup.py#L8) so bleach doesn't conflict with my other packages (and severely complicate deployment)? That would make my life a lot easier.

I'm also happy to create a PR that does exactly that if you don't have the time, or if you just want to click the one-click merge button. I'm also happy to help maintain bleach more generally if need be. I'm already the GitHub/PyPI maintainer of a few other projects that needed help - being unemployed has its benefits. 😆

**Comment by willkg** [comment]
@blag If html5lib hasn't changed much since July, I'm not sure I understand why they haven't done a release, yet. I'd rather they did a release and then we figure our stuff out based on that.

Regarding maintenance, I could use help with bugs. bleach 1.5 is probably the next release and it's waiting on these:

https://github.com/mozilla/bleach/milestone/5

If you could look into issue #161 or #200 or both, that'd be really helpful!

**Comment by blag** [comment]
> I'm not sure I understand why they haven't done a release, yet.

I don't understand either.

> I'd rather they did a release and then we figure our stuff out based on that.

Me too, but I don't expect them to have a release any time soon.

I'll try to look into those issues soon.

**Comment by kitterma** [comment]
It would be nice to see support for working with html5lib with 8 or 9 9s.  I have a project that already depends on the newer APIs, so just using the older html5lib isn't going to work for me.  I can do something ugly if I need to to get by, but it'd be even nicer to see bleach working with the newer html5lib.

**Comment by mdxs** [comment]
Just noted that it is being worked on: see https://github.com/mozilla/bleach/issues/229#issuecomment-268092460

**Comment by willkg** [comment]
This is done, so I'm going to close this out.
