### ISSUE TITLE
TLD list is not comprehensive and is outdated affecting linking

### ISSUE THREAD

**Issue by willkg** [mozilla/bleach#223]
bleach has a hard-coded set of TLDs that it uses for the `url_re` which is used for linkifying.

The problem with this is that it's not updated and it's not exposed to devs so they have no ability to adjust it.

PR #159 covered adding some infrastructure to provide an updated list along with infrastructure to update the list for your local copy of bleach.

However, I think that's not a road I want to go down.

I've been wrestling with a few aspects of that PR and general direction:

1. If we land this or something like it, how do we maintain a list of TLDs going forward? Does that require us to do regular releases? Does that require us to do releases that are solely a TLD update? 
2. Are there security issues around TLDs that would be better served by separating maintenance of a list into a separate project?
3. This PR provides a command to update the TLD list, but we have no insight as to whether that operation is successful. It might be successful now, but what if it fails tomorrow? Will a user know that it's bad? Is there a way for a user to verify it? What's our responsibility for making sure it always works correctly?

I think requests has a similar situation where they used to have CA bundles in the requests package and then split that out into a separate project called certifi. Then certifi updates can come out independently of requests and it provides a nice API for people to use their own CA bundles.

I think treating this the same way is worth looking into. I want to take a look around to see what the current state of TLD-related Python libraries is and maybe we should use one of them.

This issue covers researching other TLD-related Python libraries--can any of them provide a certifi-like function for bleach? If so, let's do that. If not, then we'll probably have to start one ourselves.

**Comment by EmilStenstrom** [comment]
Alternatives:
* tld: https://pypi.python.org/pypi/tld
* tldextract: https://pypi.python.org/pypi/tldextract
* publicsuffix: https://pypi.python.org/pypi/publicsuffix/
* publicsuffixlist: https://pypi.python.org/pypi/publicsuffixlist/
* dnspy: https://pypi.python.org/pypi/dnspy/

None of them release a new version every time there is an update to the tld list. If we want that we need to build it. Instead they either require that the user supplies an updated list of that you run an update script before you get started. 

Notes:
* tldextract handles the [differences between ICANN domains and Private domains](https://github.com/john-kurkowski/tldextract/issues/19) properly (exclude the private ones)
* dnspy hasn't been updated since 2013.
* dnspy does not support python 3.
* All of them have permissive licences (MPL, BSD, or MIT).

I think tldextract looks like the best option if we should use an external library.

Resources:
* List of public suffixes: https://publicsuffix.org/list/public_suffix_list.dat
* List of tests here: https://dxr.mozilla.org/mozilla-central/source/netwerk/test/unit/data/test_psl.txt?raw=1

**Comment by willkg** [comment]
I've though about this on and off for a while in relation to maintenance burden for me since that's the big blocker on everything Bleach these days. Given that, I adjusted the code so it's possible to use your own list of TLDs. Then users are free to do whatever they want in regards to maintaining lists and sourcing them and all that and I'm not blocking them.

Given that, I'm going to close this out.

**Comment by philippbosch** [comment]
@willkg In the meantime, somebody has come up with a list of TLDs as a Python package that is updated automatically every time the official IANA list changes: https://pypi.org/project/tlds/

Would you be open for a PR that uses that package to replace the hard-coded list of TLDs?

**Comment by g-k** [comment]
> Would you be open for a PR that uses that package to replace the hard-coded list of TLDs?

No I don't think so. I could be completely wrong, but I don't think most bleach users use linkify with the latest version of TLDs. So for Mozilla sites and probably most other bleach consumers I think it poses an extra unnecessary risk.

For example, at build time `tlds` currently [fetches the list via http](https://github.com/kichik/tlds/blob/master/setup.py#L8-L19) then writes it to a set in [a python source file](https://github.com/kichik/tlds/blob/bb10a8d2d2dbe2c8736eb3160303691de6dbb32a/setup.py#L31-L32). Using it adds dependencies on:

* the tlds maintainer (do they have 2FA enabled on their pypi account? how secure is their email account used for recovery? etc.)
* the hosting provider and admins of http://data.iana.org/
* being able to resolve and make an HTTP request to http://data.iana.org/TLD/tlds-alpha-by-domain.txt without it being hijacked

Other TLD packages would at a minimum add the first dependency.

I think it's best for bleach to not track TLDs, we'll ship the current list but not add new TLDs and make it easier for people to use their own TLD lists (from other packages or what have you).

Initially I'll add an example to the docs on how to use linkify with a custom TLD list, and if the API isn't ergonomic we can work on improving it.
