### ISSUE TITLE
Support cleaning HTML for presentational purposes

### ISSUE THREAD

**Issue by EmilStenstrom** [mozilla/bleach#234]
In #67 there was a discussion about adding more attributes to the clean method to allow stripping the contents of disallowed tags, and not only the contents. I think this would be a great idea, and would allow us to remove other cleaning we do today.

Our use-case is that we receive unsafe e-mail messages. Some of them are full HTML documents, but most are just HTML fragments. They are extremely messy, and we want to pick out the content and a few well-specified formatting tags from the contents of that HTML. Using clean() doesn't work since it keeps the contents of for instance `<script>` tags, so we've implemented a separate cleaning step that uses lxml.html.clean. Cleaner for this. This is not specific to script tags, style tags are also affected.

In #67 it was suggested that this new methods was called `prettify`. What's needed to continue the discussion if this is a good idea?

**Comment by dangayle** [comment]
Also here: https://github.com/mozilla/bleach/issues/185

**Comment by dangayle** [comment]
This is important. Stripping unsafe tags is a safety feature, I get that, but it's gross to leave the javascript text (or other unwanted text node) still visible. Without this, we would either have to roll our own or use an entirely different library to accomplish both tasks, which undermines the usefulness of bleach.

**Comment by tgs** [comment]
The filter API in html5lib seems pretty useful here.  `<style>` and `<script>` are special because they can't have child tags, so the logic can be very simple:

```python
import sys
import html5lib
from html5lib.filters.base import Filter


class NoChildTagFilter(Filter):
    """
    ONLY WORKS ON TAGS THAT CANNOT HAVE CHILDREN
    """
    def __init__(self, stream, tags):
        Filter.__init__(self, stream)
        self._tags = [t.lower() for t in tags]

    def __iter__(self):
        tokens = Filter.__iter__(self)
        while True:
            for token in tokens:
                if token['type'] == 'StartTag' and token['name'].lower() in self._tags:
                    break
                yield token
            else:
                # we ran out of tokens
                break
            for token in tokens:
                if token['type'] == 'EndTag' and token['name'].lower() in self._tags:
                    break


if __name__ == '__main__':
    dom = html5lib.parseFragment(sys.stdin.read(), treebuilder="dom")
    walker = html5lib.getTreeWalker("dom")
    stream = walker(dom)

    s = html5lib.serializer.HTMLSerializer()

    sys.stdout.write(s.render(NoChildTagFilter(stream, ('script', 'style'))))
```

I haven't tried any really fiendish examples on this yet, but if you're relying on the sanitizer *after* this filter, I think it would work well.

**Comment by jvanasco** [comment]
Another use case is how whitespace is affected, such as when dealing with formatting in `<pre>` tags or large segments of text.

In the second, more obtuse case, we often have text that has 30% fewer lines when bleached.  All the bleached lines become newlines (`\n`) which is useful for source-mapping, but often we would prefer to "collapse" away lines that are removed.

**Comment by EmilStenstrom** [comment]
@jvanasco Wouldn't it be easier to remove lines with just whitespace afterwards?

The main use case here is the contents of script and style tags, and there's no way to remove that text after the surrounding tags have been removed.

**Comment by jvanasco** [comment]
Sorry I missed this comment (a year ago!)

First - I'm very much +1 to removing the contents of script/css/iframe tags.  The only way we're able to do that is to run an HTML parser to strip it first, then run `bleach` afterwards - which is a ridiculous approach as we need to parse the content twice and is incredibly inefficient.  I really think this should be part of the `clean` function via a flag as in the original ticket.

In terms of my comment above, I should clarify.  whitespace within PRE tags in HTML is always significant; whereas whitespace within other parts of HTML is often insignificant (though it may not be, depending on the context).  the only way to display-safely remove whitespace lines is to do so within a parser. 

I may want to only collapse "excluded" lines outside of a PRE tag ("excluded" is where there is a "source" value, but not a "cleaned" value), but I may also want to collapse "excluded" lines within PRE tags.  Even if I wanted to collapse the lines within the PRE tag- because of whitespace significance, I would likely only want to exclude those lines which bleach stripped, while including the whitespace lines which were specifically entered.

for a use-case, imagine a comment in a GitHub issue like this one:

* lines 0-10: overview
* lines 10-30: "unsafe html" to be cleaned away
* lines 30-50: a "pre" formatted code block

stripping duplicate whitespace in lines 0-30 should not affect rendering, but stripping it away in 30-50 will alter the display.

**Comment by jvanasco** [comment]
FWIW I created a new package `bleach_extras` on pypi and github (https://github.com/jvanasco/bleach_extras) to support this.

The functionality is handled by invoking a `bleach.Cleaner` with a custom post-processing Sanitizer filter.:
* specifying tags to strip
* whitelisting those tags in the normal bleach filter
* stripping the tag+contents (characters in the node and the entire sub-tree) within `Cleaner.clean` during the 'filters' step

Tags can be customized by creating custom subclasses of the `TagTreeFilter` class in the module, and the content can be replaced with an 'unsafe' marker if desired.

The goal was to remove the overhead of parsing/tokenizing the fragment a second time. It only adds about 10% more execution time in benchmarks - vs doubling the time through other methods. we used a band-aid by removing the content on an initial pass via a first text processor (similar to the code example above), but that made the bulk of execution time in 'comment  submission' forms parsing an html fragment multiple times.  the staging and bench servers are much happier now, I haven't deploy to production yet.

I understand the `bleach` project considers this "prettification", but I consider this within the scope of "security".  [I also don't see any difference between this and stripping a disallowed tag vs html encoding it].  

I'm hoping others will consider contributing to my package with edgecases and fixes if needed.

**Comment by EmilStenstrom** [comment]
@jvanasco Wow! This looks great. It will allow our team to remove an extra parsing step we have implemented today, and cut the parsing time by 2. Thanks so much for your contribution!

**Comment by benzkji** [comment]
@jvanasco any chance this could get included into bleach itself?

**Comment by jvanasco** [comment]
@benzkji the bleach maintainers have narrowed the scope of this project over the years. while i'd love for that functionality - and several others - being part of it, it realistically will not happen.

**Comment by benzkji** [comment]
@jvanasco thanks, that clears up!

**Comment by g-k** [comment]
Closing as out of scope. Try jvanasco's `bleach_extras` mentioned in https://github.com/mozilla/bleach/issues/234#issuecomment-430799443
