### ISSUE TITLE
Please document difference between BleachSanitizerFilter and html5lib’s sanitizer.Filter

### ISSUE THREAD

**Issue by stucox** [mozilla/bleach#277]
It’s not clear what the difference is between using Bleach’s sanitizer and the one which ships with html5lib.

`BleachSanitizerFilter` inherits from `html5lib.filters.sanitizer.Filter` and overrides the `sanitize_token()`, `allow_token()` and `sanitize_css()` methods, but even reading the code isn’t entirely obvious what the functional difference is.

It does have a slightly different API and different defaults — are they the only differences? Or given equivalent config (tags, attributes, etc), would they give the same output?

If not, in what way(s) is Bleach’s version better?

**Comment by willkg** [comment]
Sure! Actually, one of the things I did for Bleach 2.0 was restructure Bleach's sanitizer so it was easier to compare the two. Sounds like I didn't do a good enough job on that. Sorry!

Bleach's sanitizer allows for a map for `ALLOWED_ATTRIBUTES` giving you a lot more control over sanitizing attributes: you can sanitize attributes for specific tags, you can sanitize based on value, etc.

Bleach's sanitizer always alphabetizes attributes, but uses an alphabetizer that works with namespaces--the html5lib one is broken in that regard.

Bleach's sanitizer always quotes attribute values because that's the safe thing to do. The html5lib one makes that configurable. In this case, Bleach doesn't make something configurable that isn't safe.

Bleach's sanitizer has a very restricted set of `ALLOWED_PROTOCOLS` by default. html5lib has a much more expansive one that I claim is less safe.

`html5lib.filters.sanitizer.Filter`'s `sanitize_css` is broken and doesn't work.

There are probably some other differences, but they're more minor.

Hope that helps!

**Comment by stucox** [comment]
This is great, thanks. I’ve raised PR #278 to discuss adding this to the README.

Will close this off; further discussion can happen on the PR.
