### ISSUE TITLE
empty result for <body> tag

### ISSUE THREAD

**Issue by pabloleo** [mozilla/bleach#282]
Hi guys, I'm newbie for bleach. I noticed this:
my conf:
- python ==2.7  
- bleach==2.0.0
- html5lib==0.999999999 (9 9s)

this is my code:

```
bleach.clean(u'<body class="foo" style="color: red;">',
    tags=['body'],
    attributes=['style'],
    styles=['color']
)
```

but my result is `''` why?
Thank u for your time 
Paolo

**Comment by willkg** [comment]
I think you're bumping up against a non-goal for Bleach. Bleach is intended for cleaning fragments rather than entire HTML documents. Bleach uses HTMLParser's `parseFragment` (https://html5lib.readthedocs.io/en/latest/html5lib.html#html5lib.html5parser.HTMLParser.parseFragment) which won't try to add all the missing tags to make a well-formed document rather than `parse` (https://html5lib.readthedocs.io/en/latest/html5lib.html#html5lib.html5parser.HTMLParser.parse) which does.

If you need to clean entire documents, you could probably write your own `Cleaner` class that uses `parse` rather than `parseFragment`. That happens on this line:

https://github.com/mozilla/bleach/blob/master/bleach/sanitizer.py#L133

Let me know if that helps!

**Comment by pabloleo** [comment]
Thank u for reply, 
my goal is to work on fragments:
```
bleach.clean(u'<p>Hi <strong>WillKg</strong></p>',
    tags=['p'],
    attributes=['style'],
    styles=['color'],
    strip=True
)
```
the result is ok: it's a fragment? 
`<p>Hi <strong>WillKg</strong></p>`

but <body> for Bleach cannot be considered a fragment? 
`<body>Hi <strong>WillKg</strong></body>`

i don't want a well-formed document. 
Sorry but I'm confused ...

**Comment by willkg** [comment]
An HTML fragment is a string of HTML that you might find in an HTML document inside the `<body>` tag, so it won't include `<html>`, `<head>`, `<body>`, and some of the other tags you might find defining the document. `parseFragment` will drop those tags from the fragment.

Why do the strings you're trying to clean include `<body>` tags?

**Comment by pabloleo** [comment]
Unfortunately I've this:
`<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">`
i'd like to remove non supported attributes in HTML5....

**Comment by willkg** [comment]
I'm not sure I understand what you're trying to do.

Where does that string come from? Is it user-generated content? Is it a blog comment? Something else?

When you say "non-supported attributes in HTML5", that sounds like you're not trying to sanitize the string and taking out things that could be XSS attacks or malicious content. It sounds more like you're trying to make sure the string is valid HTML5. Does that sound right?

**Comment by pabloleo** [comment]
it's an old website in .jsp that contains this attributes... yes i want to sanitize (clear) the pages for html5. maybe i don't understood library goal. Sorry for my English.

**Comment by willkg** [comment]
Ahh... ok. Bleach is really a security library for sanitizing text and removing malicious content. I think it'll be hard to use for this purpose.

When I was doing web development with JSP and Java, we used Tidy:

http://www.html-tidy.org/

I think that might meet your needs better. Let me know if that helps!

**Comment by pabloleo** [comment]
Thank u very much for the support and your time. I appreciate your advice.
