### ISSUE TITLE
Wrong output on passing "<>" to clean method

### ISSUE THREAD

**Issue by karthiksai19** [mozilla/bleach#347]
Imported Cleaner from bleach.sanitizer
chlorine=Cleaner(tags=[], attributes=[], styles=[], protocols=[], strip=True, strip_comments=True)
print(cleaner.clean("<>")) gives the output in the image

![bleach](https://user-images.githubusercontent.com/35569230/35103795-f620db18-fc8c-11e7-9610-c9af9684ca34.png)

**Comment by willkg** [comment]
What were you expecting it to output?

**Comment by karthiksai19** [comment]
Either "<>" or an empty string is what I was expecting. Please tell me if I'm wrong? Thank you.

**Comment by willkg** [comment]
`<>` isn't an HTML tag (there's no text between the characters) and thus it's treated as a `<` followed by a `>`. After tokenizing and parsing, that gets escaped to `&lt;&gt;` because those characters should get escaped when they're not part of an HTML tag.

I think Bleach is doing the right thing here.

Hope that helps!
