### ISSUE TITLE
linkify() "fixes" HTML by adding or removing tags

### ISSUE THREAD

**Issue by Deimos** [mozilla/bleach#392]
Similar to the issue in https://github.com/mozilla/bleach/issues/280, `bleach.linkify()` seems to be "fixing" HTML by adding or removing tags if it interprets something as an HTML tag.

For example:

```
>>> bleach.linkify("insert <name> here")
'insert <name> here</name>'

>>> bleach.linkify("Well that's just great</sarcasm>")
"Well that's just great"
```

**Comment by willkg** [comment]
I don't think this is fixable. The thing I fixed with clean is that it uses a special parser and tokenizer and passes the list of allowed tags to them and the tokenizer (ab)uses that knowledge and converts anything not in the allowed list of tags into a Characters token.

If you do linkification as part of cleaning (see https://bleach.readthedocs.io/en/latest/linkify.html#using-bleach-linkifier-linkifyfilter), then that should work fine. Linkifcation wouldn't be doing any parsing--it just hangs off of the html filtering after the sanitization step. Everything should work fine.

Your two examples plus a third that has a linkable url:

```
> python
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bleach import Cleaner
f>>> from bleach.linkifier import LinkifyFilter
>>> cleaner = Cleaner(filters=[LinkifyFilter])
>>> cleaner.clean('insert <name> here')
'insert &lt;name&gt; here'
>>> cleaner.clean('well that is just great </sarcasm>')
'well that is just great &lt;/sarcasm&gt;'
>>> cleaner.clean('need an exmaple with a link to http://example.com/')
'need an exmaple with a link to <a href="http://example.com/">http://example.com/</a>'
>>> 
```

If you're doing linkification on its own, then there's no concept of "allowed tags". It doesn't use the special parser or tokenizer that ignores non-allowed tags. So then the parser thinks they're all tag tokens and fixes the HTML.

Going back a step, I don't think one should ever linkify without also fixing the HTML. How would you know that what you end up with is correct and safe and not HTML soup? Are there real use cases for linkifying without cleaning?

**Comment by willkg** [comment]
I think I worked out a fix. I'm toying with it now to see if it creates new problems or not. I'll try to include it with Bleach 3.0.
