### ISSUE TITLE
bleach.clean method returns unexpected value for string with unknown entities

### ISSUE THREAD

**Issue by aliaksandr-trush** [mozilla/bleach#450]
For string strings like "&adp;" and "&*!;" actual output is "&ad;;" and "&*;;".
But I expect that such values should remain original value ("&adp;" and "&*!;" corresponding).

**Comment by g-k** [comment]
Hey @aliaksandr-trush! Thanks for reporting this. `bleach.clean` does not retain the original values for entities html5lib doesn't recognize (see https://github.com/mozilla/bleach/blob/77e1acdb863e59a1b6494ffa6e9d304a79f0403c/bleach/sanitizer.py#L395 and https://github.com/mozilla/bleach/blob/77e1acdb863e59a1b6494ffa6e9d304a79f0403c/bleach/_vendor/html5lib/constants.py#L651 for the list of recognized entities).

Are there specific values you expect it to retain? Generally speaking we'd like clean should remove or escape unparseable HTML.

**Comment by alvinlindstam** [comment]
I took a look at this, and found a possible bug, I attempted a fix at https://github.com/mozilla/bleach/pull/452

I noticed that the library is not using the `resolve_entities` and `consume_entities` features of html5lib, and implements it's own html entity sanitizer. Do you know why that is? What difference is it that we want to achieve compared to letting them parse the entities and produce valid entity output?

**Comment by willkg** [comment]
> Do you know why that is? What difference is it that we want to achieve compared to letting them parse the entities and produce valid entity output?

html5lib is an html5 parser and *consumes* the entities it recognizes. When we rewrote Bleach to use the Filter API, that caused a bunch of regressions from prior Bleach behavior. So I wrote a bunch of code to override those parts of the html5lib parser and tokenizer so they didn't consume entities and let Bleach sanitize properly.

**Comment by willkg** [comment]
I think the problem is here:

https://github.com/mozilla/bleach/blob/47fe22e72dd4b2f54b1dd6bccfdc3eee212675c5/bleach/html5lib_shim.py#L499-L506

That consumes from the stream until it the thing it's assembling is definitely not a known character entity and the character it's going to look at is not an end character.

With `&adp;`, we have this:

```
   stream               c     possible_entity
0  ['d', 'p', ';']      a 
1  ['p', ';']           d     a
2  [';']                p     ad
```

At that point, `ad` is not a prefix of an entity, so it drops out of the loop. We lose `p` because it wasn't appended to `possible_entity` and it's no longer in the stream (that's actually a little more complicated--more in a bit). The next character is a `;`, so it thinks it got an entity so it returns `ad`.

This is called in `sanitize_characters`, so it gets `ad` and appends that as an `Entity`token. It needs to fix the stream, so it slurps up what it thinks is `&ad;`, but it's really `&adp` and the stream retains the `;`. Then when it's serialized, the serializer prepends a `&` and appends a `;` and the final stream is `&ad;;`.

The fact that `&xx;` works is a fluke. If we used `&xxx;` in the tests, it'd be more obvious that it's failing since it becomes `&xx;;`.

I think what we want is this where `clean` doesn't consume or change it at all:

```
>>> from bleach import clean
>>> clean('&adp;')
'&adp;`
```

I'll think more about how to fix this, but I don't think #452 works because it changes the behavior in ways we don't want.

**Comment by DylanYoung** [comment]
What were the regressions from prior bleach behaviour?  Seems like an important question to answer.

**Comment by willkg** [comment]
@DylanYoung you should read through the closed issues and pull requests. The details you want are there.

**Comment by DylanYoung** [comment]
What would that benefit anyone exactly?

**Comment by willkg** [comment]
Quick sum up of this issue. There are two bugs here:

1. When the text contains a thing that is not a character entity, but starts with a & and ends with a ;, then a character gets dropped and an additional ; gets erroneously added.
2. Things that are not character entities but start with a & and end with a ; should have had the & escaped, but that wasn't happening.

PR #647 fixes both of those bugs. This issue should be fixed now. Further, the tests are clearer about what it is they're testing and expecting.
