### ISSUE TITLE
Ability to turn relative URLs into absolute

### ISSUE THREAD

**Issue by vporton** [mozilla/bleach#457]
Add the ability to turn relative URLs into absolute by adding a specified prefix.

**Comment by g-k** [comment]
Hi @vporton, this should be possible with a linkify callback or filter. Try the second example at  https://bleach.readthedocs.io/en/latest/linkify.html#setting-attributes 

Closing since bleach doesn't try to prettify content by default: https://bleach.readthedocs.io/en/latest/goals.html#make-malicious-content-look-pretty-or-sane
