### ISSUE TITLE
Bleach cleaning allowed tags

### ISSUE THREAD

**Issue by deltaGPhys** [mozilla/bleach#480]
I've set, in `settings.py`:
```
bleach.sanitizer.ALLOWED_TAGS = ['p','br','b','u','ul','li','font']
bleach.sanitizer.ALLOWED_ATTRIBUTES = {'font':['size']}
```

When I use it to clean up form input, as below, it uses the default list (in particular, removing `<font>` and `<br>`) of allowed tags, even though the last line correctly outputs the list above. Yes, I know that there's a bleach input field; I'm trying not to change my models.
```
if form.is_valid():
                form.save()
                this_standard.Description = bleach.clean(this_standard.Description)
                this_standard.save()
                print bleach.sanitizer.ALLOWED_TAGS
```
If I manually pass the variables, it works:
```
this_standard.Description = bleach.clean(this_standard.Description,tags=bleach.sanitizer.ALLOWED_TAGS, attributes=bleach.sanitizer.ALLOWED_ATTRIBUTES)
                
```

**Comment by g-k** [comment]
Hi @deltaGPhys, which python, bleach, and django versions are you using?

**Comment by deltaGPhys** [comment]
Hi :)

Python 2.7, Django 1.9, Bleach 3.1.0

It's working brilliantly otherwise - love it!

**Comment by g-k** [comment]
Thanks! 

OK so, `ALLOWED_TAGS` is a constant and as you noticed modifying it and other constants won't change bleach's behavior since it creates a new variable in memory that bleach has no way of knowing about i.e. 

settings.py:

```python
import bleach.sanitizer

print(id(bleach.sanitizer.ALLOWED_TAGS))  # id prints the memory address for CPython

bleach.sanitizer.ALLOWED_TAGS = ['p','br','b','u','ul','li','font']
print(id(bleach.sanitizer.ALLOWED_TAGS))
```

```console
python2.7 ~/settings.py
140621293125432
140621293134696
```

^ the above addresses will vary per run, but the point is they aren't equal.

It is a good idea to keep your `ALLOWED_TAGS` in one place like `settings.py` to have one place to update. I'd recommend reimporting that setting (`from django.conf import settings` then `settings.BLEACH_ALLOWED_TAGS` or something) and passing it to `bleach.clean` in your views/template helpers.

Hope that makes sense

**Comment by deltaGPhys** [comment]
Ah, got it. So there's no way to modify the default tags and attributes, and I'll always need to explicitly pass some variable to the function?

**Comment by g-k** [comment]
Yeah, I don't have a clean way to set it via the pkg globals.

**Comment by deltaGPhys** [comment]
Cool, it still works, so that works for me - thanks again!
