### ISSUE TITLE
add support for CDATA in mathml and svg contexts

### ISSUE THREAD

**Issue by mitar** [mozilla/bleach#510]
As described [on Wikipedia](https://en.wikipedia.org/wiki/CDATA#Syntax_and_interpretation), I would assume that sanitizing:

```
<![CDATA[<sender>John Smith</sender>]]>
```

returns:

```
<![CDATA[<sender>John Smith</sender>]]>
```

or:

```
&lt;sender&gt;John Smith&lt;/sender&gt;
```

But in fact it returns (with `strip=False`, and `sender` not on the list of allowed tags):

```
John Smith&lt;/sender&gt;]]&gt;
```

or (with `strip=True`):

```
John Smith]]&gt;
```

Tested with `bleach==3.1.0`.

`CDATA` can be used in HTML5: https://html.spec.whatwg.org/multipage/syntax.html#cdata-sections

**Comment by chasebrewsky** [comment]
I'm having a similar issue after updating from `2.1.4` to `3.1.1`. We have a test that originally expected the string:
```
<SCRIPT>document.write("<SCR =C2=BB I");</SCRIPT>PT =C2=BB SRC=3D"
http://ha.ckers.org/xss =C2=BB .js"></SCRIPT>
```
to transform into:
```
document.write("&lt;SCR =C2=BB I");PT =C2=BB SRC=3D"
http://ha.ckers.org/xss =C2=BB .js"&gt
```
But now we're getting:
```
document.write("PT =C2=BB SRC=3D"
http://ha.ckers.org/xss =C2=BB .js"&gt;
```
I was going to open my own issue but there seems to be a similar pattern with the parsed CDATA issue where it strips anything that resembles an opening and closing script, regardless of it's placement in the document. It might indicate that the parser become a bit more greedy between the major version upgrade.

I'll be staying on `2.1.4` for now until either the issue is resolved or when I have time to open a pull request with a potential fix. We use the cleaned data to analyze potential XSS attacks and we can't do that if the data is incomplete.

**Comment by willkg** [comment]
CDATA isn't valid in HTML5 except in foreign contexts. I haven't done much work making Bleach clean work with MathML or SVG, so I don't know what the support is like. Maybe we need to improve MathML support? I don't think anyone has asked for that.

**Comment by willkg** [comment]
We're not going to fix this. Sorry!

**Comment by mitar** [comment]
Why? I mean, the problem is that this library is about cleaning unknown HTML input, how can I control if the input has CDATA in the wrong place? But having `<![CDATA[<sender>John Smith</sender>]]>` be converted to `John Smith&lt;/sender&gt;]]&gt;` really breaks all expectations. At least make it return `&lt;sender&gt;John Smith&lt;/sender&gt;
`.

**Comment by willkg** [comment]
I didn't think it was clear what should happen here and no one replied for a year and a half to the last comment which suggests to me that while it may be an issue, it's something everyone who is using Bleach is living with.

This project is deprecated, so I went through and closed all the bugs I don't plan on fixing.

If you want to work on a PR, I'm game for looking at it, but probably won't get to it until I do another maintenance cycle when Python 3.13 comes out.

**Comment by mitar** [comment]
Oh, I missed that the project is deprecated. That makes sense then.
