### ISSUE TITLE
Bleach doesn't handle whitespace in iframe tag correctly

### ISSUE THREAD

**Issue by liavkoren** [mozilla/bleach#541]
```
In [30]: bleach.clean('<iframe> </ iframe>', tags=['iframe'])
Out[30]: '<iframe> &lt;/ iframe&gt;</iframe>'

In [31]: bleach.clean('<iframe> </iframe>', tags=['iframe'])
Out[31]: '<iframe> </iframe>'
```

Using bleach 3.1.4 and python 3.7.5

**Comment by willkg** [comment]
The first is invalid HTML5 end tag:

* https://dev.w3.org/html5/spec-LC/syntax.html#syntax-end-tag
* https://html.spec.whatwg.org/multipage/parsing.html#end-tag-open-state

The tokenizing is happening in the html5lib parser, so I think this should get fixed there. However, since fixing this would be contrary to the html5 browser parsing spec, I don't think it would result in a change to html5lib.

It might be possible to fix this in Bleach's html5lib shim where we override some of the html5lib behavior, but my gut feeling is that this is going to be hard to do and I think we shouldn't try unless there was a compelling reason/use case to do so.

**Comment by liavkoren** [comment]
Isn't it a vuln, if the point of bleach is to sanitize untrusted input and all I have to do to get around the sanitation is to add some whitespace? Maybe I'm being a dummy here, but.. seems bad? I could totally be wrong, I haven't thought about this in the two years since I opened this issue.

**Comment by willkg** [comment]
I don't understand how your example gets around sanitization by adding whitespace. Can you clarify what you mean?

**Comment by willkg** [comment]
I don't think there's anything we should do here and I don't see how this denotes a security issue.

If you think this is a security vulnerability, please follow the security bug report process: https://github.com/mozilla/bleach/blob/main/SECURITY.md
