### ISSUE TITLE
contents of script tag isn't getting sanitized correctly

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#561]
There was an undocumented change/regression that I traced back to the bleach 3.1.1 security fix.

html entities within a `script` tag before 3.1.0 were not escaped.
starting in 3.1.1, they are escaped.

I do not think this affects anything practical or that it should be changed; we just have extensive tests that check against malformed payloads and picked this up... it took a while to track down what broke and why.

an entry in the changelog would be nice, to save others time.

bleach 3.1.0

    >>> import bleach
    >>> bleach.clean('a <script>safe(); foo="<a>"; <div>foo</div></script> example', tags=["script"])
    'a <script>safe(); foo="<a>"; <div>foo</div></script> example'

bleach 3.1.1

    >>> import bleach
    >>> bleach.clean('a <script>safe(); foo="<a>"; <div>foo</div></script> example', tags=["script"])
    'a <script>safe(); foo="&lt;a&gt;"; &lt;div&gt;foo&lt;/div&gt;</script> example'

**Comment by willkg** [comment]
This is a bug that should get fixed.

**Comment by willkg** [comment]
I don't think this is something I'm going to fix for 5.0.0, so I'm bumping it out of the milestone.

**Comment by willkg** [comment]
I skimmed through the serializer code. The tokenizer/parser label the data between the `<script>` tags as characters data. The serializer sees that and if `escape_rcdata` is True (which it is), then it escapes characters tokens. It doesn't treat `<script>` differently.

It might be possible to implement `escape_rcdata` ourselves in the `BleachHTMLSerializer` without making everything really complicated. It's tricky because by the time our serialize code sees the token, it's not a token anymore and we've lost a lot of meta information. But maybe we have enough information to determine whether to escape rcdata in the correct places and handle `<script>` contents differently.

Another (gross) thing we could do is override the `rcdataElements` value just in the `bleach._vendor.html5lib.serializer` module to not include `script`. It looks like that module _only_ uses that value to know when to escape characters tokens in rcdata-content tags.

I'm not thrilled about any of these ideas, so I think I'm not going to tackle this for 5.0.1.

**Comment by jvanasco** [comment]
I'm not entirely sure this is worth fixing, ever.  While I agree it may *appear* to be a bug and that better parsing as you suggest would be idea, it is really hard for me to think of scenarios where one would want to even allow `<script>` tags in untrusted UGC.  This bug report originated from an internal test on trying to break Bleach via malformed payloads and seeing how it behaved with different settings, and if we could potentially allow users to upload content with script tags.

Theoretically, it would be great to implement things as you suggest - but I just can't think of any practical values to it right now.  I also feel this is likely an area where there will likely be future CVEs for one or more major browsers, because someone will figure out how to break a parser with it.  Both of these reasons, and probably others, are why I think it would be fine to simply note this as a breaking change (and possibly add a test to ensure this behavior stands), instead of considering it a regression.

**Comment by willkg** [comment]
We're not going to change this. If someone wants to add a note about how script tag contents are escaped, I'd accept a PR.
