### ISSUE TITLE
feature: expand tests with urls that implement all RFC components and characters, and some edge contexts

### ISSUE THREAD

**Issue by jvanasco** [mozilla/bleach#562]
The tests that go against various link forms ( such as https://github.com/mozilla/bleach/blob/master/tests/test_linkify.py#L324-L329 ) use the most popular RFC components, but should probably feature more advanced urls.

For example, the last path component can have semicolon delimited params (which no one ever uses)

    - https://user:pass@ftp.mozilla.org/x/y.exe?a=b&c=d&e#f
    + https://user:pass@ftp.mozilla.org/x/y.exe;a;b=c;d=e?a=b&c=d&e#f

We've also had some issues with de-duplication of params or paths in the past (not by this library)

    - https://user:pass@ftp.mozilla.org/x/y.exe;a;b=c;d=e?a=b&c=d&e#f
    + https://user:pass@ftp.mozilla.org/x/x/yy/yy.exe;a;b=c;d=e?a=b&a=b&c=d&e#f

There are a few more valid things that can be stuffed in, + and percent encoding in query params; some valid chars in the hash/anchor.

With limited testing I did, bleach currently does everything right and as expected.  I just think the various test suites could do with some more cases to catch future issues.

**Comment by g-k** [comment]
Yeah, I'd love to land some test cases to cover more of the possible URLs.

Especially since there have been some cpython changes URL parsing changes (maybe https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote).

I'd love to move the clean and linkify tests to [miniformats](https://blog.nelhage.com/2016/12/how-i-test/#design-miniformats-for-test-input-and-output) and started that for clean, but pytest parametrize is working fine for now too.

**Comment by willkg** [comment]
No one's worked on this in 3 years, so I'm going to close it out.
