### ISSUE TITLE
bug: `bleach.clean` strips some allowed tags

### ISSUE THREAD

**Issue by ZugBahnHof** [mozilla/bleach#569]
When trying to sanitize html with custom allowed tags, not all of them are actually untouched, some just get removed entirely. In my case, this happenend to `td` and `tr` but not to `em`.

 - Python Version: [e.g. 3.8.6]
 - Bleach Version: [e.g. 3.2.1]

### Reproduce

```python
from bleach import clean

html = """
 <table style="width:100%">
  <tr>
    <td>Firstname</td>
    <td>Lastname</td>
    <td>Age</td>
  </tr>
</table>

<a href="https://example.org">This is a Link!</a>

<div class="center">
    <em>Foo</em> Bar!
</div>
"""

print(clean(html, tags=["tr", "td", "em"], strip=False))
```

## Expected output:
```html
 &lt;table style="width:100%"&gt;
  <tr>
    <td>Firstname</td>
    <td>Lastname</td>
    <td>Age</td>
  </tr>
&lt;/table&gt;

&lt;a href="https://example.org"&gt;This is a Link!&lt;/a&gt;

&lt;div class="center"&gt;
    <em>Foo</em> Bar!
&lt;/div&gt;
```
## Actual output
```html
&lt;table style="width:100%"&gt;
  
    Firstname
    Lastname
    Age
  
&lt;/table&gt;

&lt;a href="https://example.org"&gt;This is a Link!&lt;/a&gt;

&lt;div class="center"&gt;
    <em>Foo</em> Bar!
&lt;/div&gt;
```

**Comment by g-k** [comment]
huh, that's weird. Thanks for the report! I can reproduce this on Bleach 3.2.1/Python 3.8.6.

html5lib inserts a `tbody` after the `table`, which might be confusing bleach.

**Comment by willkg** [comment]
I think what's going on is that the tokenizer sees `table` tag, escapes it thus converting it to characters token type here:

https://github.com/mozilla/bleach/blob/c5c3f50d01967feb1f67e55ad33a6880d9dc2e73/bleach/html5lib_shim.py#L419-L423

Then the parser then sees `tr` and `td` tags and removes them because they're not descendents of a `table`.

I don't think Bleach is doing the wrong thing here. It might be better if Bleach prevented you from allowing `tr` and `td` without also allowing `table`. I don't know if I want to implement that.

I don't think we want to make any changes here.
