### ISSUE TITLE
Add the ability to restrict/rewrite URLs for href and src attributes

### ISSUE THREAD

**Issue by lieryan** [mozilla/bleach#76]
Sample use cases: in moderated sites, linking to externally-hosted images means the user can change image without the moderator's knowledge. The ability to rewrite URLs means these images can either be sanitized or copied locally (like StackOverflow did with imgur). It can also rewrite absolute urls to relative urls.

[List of HTML tag attributes which can contain URLs](http://stackoverflow.com/questions/2725156/complete-list-of-html-tag-attributes-which-have-a-url-value)

**Comment by EmilStenstrom** [comment]
Hi! This should definately be a priority in my opinion. Allowing <img> tags to have src attributes, or <a> tags to have href attributes, opens you up to all sorts of XSS problems, since you don't by default validate that the link or src points to a valid URL. 

Validating that the link is a valid URL (with one of the whitelisted protocols) would be a great first step imho.

**Comment by EmilStenstrom** [comment]
Here's an example:

```html
python -c "import bleach; print bleach.clean('<img src=\"</comment><img src=x onerror=alert(1)//\">', strip=True, tags=['img'], attributes={'img': ['src']})"
```
The output is:
```html
<img src="</comment><img src=x onerror=alert(1)//">
```
... which is clearly not sanitized.

**Comment by jsocol** [comment]
@EmilStenstrom If you think something is a functional attack against Bleach, please don't post examples in public. I'll get a better security-issue reporting email address into the readme/contributing docs today.

This, however, is not. If you plug this into a browser, there's no alert:

```html
<!DOCTYPE html>

<img src="</comment><img src=x onerror=alert(1)//">
```

That's because [attribute values can contain all those characters](http://www.w3.org/TR/html5/syntax.html#attributes-0). Attribute values aren't parsed. That HTML asks the browser to load the path `</comment><img src=x onerror=alert(1)//`, which is very nearly a valid path, too:

<img width="520" alt="image of the request in the firefox dev tools network panel" src="https://cloud.githubusercontent.com/assets/180459/9330270/41c72b64-4586-11e5-8dbc-97118c960e45.png">

Second, handling this example is already possible via [callables](http://bleach.readthedocs.org/en/latest/clean.html#callable-filters), which were documented in #77 (d61e8ee3ba3382d08ed236e7e402d048ac8179c4). They were added with the _explicit_ purpose of imposing limits on `src` attributes, like "must be from this (set of) domain(s)" or "must be relative". Or "can be parsed as a URL or path at all".

The ability to actually _replace_ the value is a nice-to-have but isn't a critical issue.

**Comment by EmilStenstrom** [comment]
Thanks for clarifying. The example is from https://html5sec.org/#38, and you're right, even the suspicion that it could be a security issue should have made me ask in private. 

I first thought this was a configuration issue, that I allowed dangerous stuff by allowing the "src" attribute in img. After experimenting some more I see that you really do remove stuff like javascript:alert(1) from img src attributes.

Somehow, I assumed that [img src] and [a href] would be automatically validated by bleach, by some default "strict" rule, that you could change via callables. I'll withdraw my request and just use callables myself.

**Comment by rshk** [comment]
I was wondering if anything new come up about this (replacing content of certain tag attributes).

My current usecase: I'm converting user-input markdown to HTML (similar to what github does for READMEs, to give an example), and I'd like to replace all the ``<img>`` ``src`` to [camo](https://github.com/atmos/camo) links.

One option could be to simply write my own function to parse the  whole tree / do the replacements, but I would like to avoid having to parse the html more than once; I had a look at `linkify()` and looks like adding an extra condition (plus a new set of callbacks) here would do https://github.com/mozilla/bleach/blob/master/bleach/__init__.py#L340

That said, it looks like that `linkify()` function is really growing huge and massively complex, so I think a better long-term approach would be to make it simpler / more extensible instead (possibly supporting the use-case of #181 as well?).

I was wondering if there are any plans about this / anyone working on it already?

**Comment by willkg** [comment]
Issue #58 talks about making it easier to extend the sanitizing pipeline with other changes. Now that Bleach uses html5lib 0.99999999, we can take advantage of the filter API to do that. That'll make it easy for people to change URIs without us having to add more maintenance burden to Bleach.

**Comment by willkg** [comment]
I added the ability to specify additional filters after sanitizing. Writing them is pretty easy. That'll cover this use case.
